### ISSUE TITLE
Display warning when some native dependency is overwriting a library from another one

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fmarot/mavennatives#1]
```
Display warning when some native dependency is overwriting a library from
another one.

For example in the lwjgl opengl library the natives for linux32 and solaris
are named the same "liblwjgl.so" so if you have both native dependencies
one is overwritten.



```

Original issue reported on code.google.com by `ruben01` on 28 Jun 2009 at 10:56

**Comment by fmarot** [comment]
This problem is partly solved now that we can autodetect the OS, and/or we can specify a suffix and an architecture in the "osFilter".
With this, we should be able to distinguish artifacts containing 64 bit .so and 32 bit .so with the same filename for example.
