### ISSUE TITLE
Add assembly config to make zip distribution file of the mavennatives plugin

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fmarot/mavennatives#2]
```
Add assembly config to make zip distribution file of the mavennatives plugin

must contain jar, pom, and sources
```

Original issue reported on code.google.com by `ruben01` on 30 Jun 2009 at 12:37

**Comment by fmarot** [comment]
Closing because starting fresh with the bug lists. A full cleanup of the M2E plugin should be made at some point.
