### ISSUE TITLE
Only copy natives for selected architectures

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fmarot/mavennatives#6]
```
It would be good to have a configuration option to only copy natives of 
specific types, e.g. linux,osx


What version of the product are you using? On what operating system?
0.0.6
Linux 64 bit
```

Original issue reported on code.google.com by `neothema...@googlemail.com` on 26 Mar 2012 at 4:12

**Comment by fmarot** [comment]
I'm closing this as it is too simple and does not fullfill my needs: I want to have a single pom and be able to unpack only windows deps on windows, linux deps on Linux and so on (adding OS architectures -x86, 64- in the mix for more fun). So for this patch to be interesting, you would have to list all the OS you actually develop for and you  would unpack in your OS libs not targetting this OS. Or you would limit the filter to one specific OS but then you would have a platform specific pom.
The changes I'm about to commit enable you to specify a list of filters for each OS. Then you will unpack only win 64 native deps on win64, only linux 32 on Linux 32 and so on...
